---

- name: Build the hello-world project
  command: >
    chdir=/tmp/kotlin-hello-world mvn clean package spring-boot:repackage
  tags: hello-world

- name: Add the executable jar into init.d
  file: src=/tmp/kotlin-hello-world/target/kotlin-hello-world-1.0-SNAPSHOT.jar
        dest=/etc/init.d/hello
        owner="root" group="root" mode=0755 state=link
  become: yes
  become_user: root
  tags: hello-world

- name: Run the hello-world
  become: yes
  become_user: root
  command: /etc/init.d/hello start
  tags: hello-world
  ignore_errors: yes
